# Generated by Django 4.2.1 on 2023-06-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='profile_pic',
        ),
    ]
